// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnb9gdbTUGUqHR3sJIM7IkXCwnr_J1dLI',
    appId: '1:821371753102:web:68fbc49f4b481c7674afdf',
    messagingSenderId: '821371753102',
    projectId: 'projectchk-46b99',
    authDomain: 'projectchk-46b99.firebaseapp.com',
    databaseURL: 'https://projectchk-46b99-default-rtdb.firebaseio.com',
    storageBucket: 'projectchk-46b99.appspot.com',
    measurementId: 'G-GZW5Q6YZWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2gPmBdmKWJek0hxPiiY9TqrjRqTU2-Dg',
    appId: '1:821371753102:android:dd5052a2948c8ebd74afdf',
    messagingSenderId: '821371753102',
    projectId: 'projectchk-46b99',
    databaseURL: 'https://projectchk-46b99-default-rtdb.firebaseio.com',
    storageBucket: 'projectchk-46b99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByyY7qkpFbAxtT8qJ_v6W_EKRr9b3vh9o',
    appId: '1:821371753102:ios:bf64acd770ac7d7e74afdf',
    messagingSenderId: '821371753102',
    projectId: 'projectchk-46b99',
    databaseURL: 'https://projectchk-46b99-default-rtdb.firebaseio.com',
    storageBucket: 'projectchk-46b99.appspot.com',
    iosBundleId: 'com.example.parkease',
  );
}
